version: "3.6"
name: yusuke-security-spike
services:
  rds:
    image: postgres
    container_name: yusuke-security-spike
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "yusuke-security-spike"
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on